# Generated by Django 3.1.2 on 2021-01-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('condiciones', models.IntegerField()),
                ('cooperacion', models.IntegerField()),
                ('supervision', models.IntegerField()),
                ('condicionesfisicas', models.IntegerField()),
                ('satisfaccion', models.IntegerField()),
                ('participacion', models.IntegerField()),
            ],
        ),
    ]
